/**
 * Lista oficial de modalidades esportivas para cadastro de árbitros
 */
export const MODALIDADES_ESPORTIVAS = [
  "Atletismo",
  "Badminton",
  "Basquete",
  "Boxe",
  "Capoeira",
  "Ciclismo",
  "Esgrima",
  "Futebol",
  "Futebol de Areia",
  "Futebol de Mesa",
  "Futebol Americano",
  "Futsal",
  "Ginástica Artística",
  "Ginástica Rítmica",
  "Handebol",
  "Halterofilismo",
  "Hipismo",
  "Jiu-Jitsu",
  "Judô",
  "Karatê",
  "Kickboxing",
  "Luta Olímpica",
  "MMA",
  "Muay Thai",
  "Natação",
  "Nado Artístico",
  "Padel",
  "Parataekwondo",
  "Pentatlo Moderno",
  "Polo Aquático",
  "Remo",
  "Rugby",
  "Skate",
  "Surf",
  "Taekwondo",
  "Tênis",
  "Tênis de Mesa",
  "Tiro com Arco",
  "Tiro Esportivo",
  "Triatlo",
  "Vela",
  "Voleibol",
  "Vôlei de Praia",
  "Xadrez",
] as const;

export type ModalidadeEsportiva = (typeof MODALIDADES_ESPORTIVAS)[number];
