-- Inserir permissões padrão dos perfis IDJuv
INSERT INTO public.role_permissions (role, permission) VALUES
  ('presidencia', 'users.read'), ('presidencia', 'users.create'), 
  ('presidencia', 'users.update'), ('presidencia', 'users.delete'),
  ('presidencia', 'content.read'), ('presidencia', 'content.create'),
  ('presidencia', 'content.update'), ('presidencia', 'content.delete'),
  ('presidencia', 'reports.view'), ('presidencia', 'reports.export'),
  ('presidencia', 'settings.view'), ('presidencia', 'settings.edit'),
  ('presidencia', 'processes.read'), ('presidencia', 'processes.create'),
  ('presidencia', 'processes.update'), ('presidencia', 'processes.delete'),
  ('presidencia', 'processes.approve'), ('presidencia', 'roles.manage'),
  ('presidencia', 'permissions.manage'), ('presidencia', 'documents.view'),
  ('presidencia', 'documents.create'), ('presidencia', 'documents.edit'),
  ('presidencia', 'documents.delete'), ('presidencia', 'requests.create'),
  ('presidencia', 'requests.view'), ('presidencia', 'requests.approve'),
  ('presidencia', 'requests.reject'), ('presidencia', 'audit.view'),
  ('presidencia', 'audit.export'), ('presidencia', 'approval.delegate'),
  ('presidencia', 'org_units.manage'), ('presidencia', 'mfa.manage'),
  ('ti_admin', 'users.read'), ('ti_admin', 'users.create'),
  ('ti_admin', 'users.update'), ('ti_admin', 'users.delete'),
  ('ti_admin', 'roles.manage'), ('ti_admin', 'permissions.manage'),
  ('ti_admin', 'settings.view'), ('ti_admin', 'settings.edit'),
  ('ti_admin', 'audit.view'), ('ti_admin', 'audit.export'),
  ('ti_admin', 'org_units.manage'), ('ti_admin', 'mfa.manage'),
  ('ti_admin', 'reports.view'),
  ('diraf', 'content.read'), ('diraf', 'content.create'),
  ('diraf', 'content.update'), ('diraf', 'documents.view'),
  ('diraf', 'documents.create'), ('diraf', 'documents.edit'),
  ('diraf', 'reports.view'), ('diraf', 'reports.export'),
  ('diraf', 'processes.read'), ('diraf', 'processes.create'),
  ('diraf', 'processes.update'), ('diraf', 'requests.create'),
  ('diraf', 'requests.view'),
  ('rh', 'users.read'), ('rh', 'content.read'),
  ('rh', 'content.create'), ('rh', 'content.update'),
  ('rh', 'documents.view'), ('rh', 'documents.create'),
  ('rh', 'documents.edit'), ('rh', 'reports.view'),
  ('rh', 'reports.export'), ('rh', 'processes.read'),
  ('rh', 'processes.create'), ('rh', 'requests.create'),
  ('rh', 'requests.view'),
  ('controle_interno', 'content.read'), ('controle_interno', 'documents.view'),
  ('controle_interno', 'reports.view'), ('controle_interno', 'reports.export'),
  ('controle_interno', 'processes.read'), ('controle_interno', 'audit.view'),
  ('controle_interno', 'audit.export'), ('controle_interno', 'requests.view'),
  ('cadastrador_setor', 'content.read'), ('cadastrador_setor', 'content.create'),
  ('cadastrador_setor', 'documents.view'), ('cadastrador_setor', 'documents.create'),
  ('cadastrador_setor', 'requests.create'), ('cadastrador_setor', 'requests.view'),
  ('cadastrador_local', 'content.read'), ('cadastrador_local', 'content.create'),
  ('cadastrador_local', 'documents.view'), ('cadastrador_local', 'requests.create'),
  ('cadastrador_local', 'requests.view'),
  ('cadastrador_leitura', 'content.read'), ('cadastrador_leitura', 'documents.view'),
  ('cadastrador_leitura', 'reports.view'), ('cadastrador_leitura', 'requests.view')
ON CONFLICT (role, permission) DO NOTHING;

-- Inserir escopos de módulos
INSERT INTO public.module_access_scopes (role, module_name, access_scope, can_create, can_edit, can_delete, can_approve) VALUES
  ('presidencia', 'servidores', 'all', true, true, true, true),
  ('presidencia', 'documentos', 'all', true, true, true, true),
  ('presidencia', 'unidades', 'all', true, true, true, true),
  ('presidencia', 'aprovacoes', 'all', true, true, true, true),
  ('ti_admin', 'usuarios', 'all', true, true, true, false),
  ('ti_admin', 'perfis', 'all', true, true, true, false),
  ('ti_admin', 'auditoria', 'all', false, false, false, false),
  ('rh', 'servidores', 'org_unit', true, true, false, false),
  ('rh', 'ferias', 'org_unit', true, true, false, false),
  ('rh', 'licencas', 'org_unit', true, true, false, false),
  ('diraf', 'financeiro', 'org_unit', true, true, false, false),
  ('diraf', 'patrimonio', 'org_unit', true, true, false, false),
  ('controle_interno', 'auditoria', 'all', false, false, false, false),
  ('controle_interno', 'relatorios', 'all', false, false, false, false),
  ('cadastrador_setor', 'servidores', 'org_unit', true, true, false, false),
  ('cadastrador_local', 'servidores', 'local_unit', true, false, false, false),
  ('cadastrador_leitura', 'servidores', 'readonly', false, false, false, false)
ON CONFLICT (role, module_name) DO UPDATE SET
  access_scope = EXCLUDED.access_scope,
  can_create = EXCLUDED.can_create,
  can_edit = EXCLUDED.can_edit,
  can_delete = EXCLUDED.can_delete,
  can_approve = EXCLUDED.can_approve;